name: card

on:
  schedule:
    - cron: "54 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: card
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Collect card
        uses: x-cmd-install/x-cmd-install-action@main
        with:
          owner-repo: openSUSE/zypper
          stages: 'card'